// Command clidocs generates the CLI reference page of the documentation site
// from the real Cobra command tree.
//
// The previous CLI pages were written by hand and listed commands and flags
// that had been renamed or removed. Walking the actual tree means the page
// cannot describe a command that does not exist, and a new command shows up in
// the documentation as soon as it is registered.
//
// Usage:
//
//	go run ./tools/clidocs -out docs/docs/reference/cli/commands.md
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/semaphoreui/semaphore/cli/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	out := flag.String("out", "", "file to write (default: stdout)")
	flag.Parse()

	root := cmd.RootCommand()
	root.InitDefaultHelpCmd()

	var b strings.Builder
	b.WriteString(`---
title: Command reference
description: "Every semaphore command and flag, generated from the command tree of the release the documentation ships with."
---

{/* Generated by tools/clidocs in the semaphoreui/semaphore repository. Do not edit by hand. */}

# Command reference

Every command, subcommand and flag the ` + "`semaphore`" + ` binary accepts, in the order
` + "`semaphore help`" + ` walks the tree. Use it to confirm a flag name or a default; the
pages next to it explain what the commands are for.

Every command reads the same configuration as the server, so point it at the right
configuration file with ` + "`--config`" + ` when you run more than one instance on a host.
See [CLI](/reference/cli) for the lookup order.

`)

	writeGlobalFlags(&b, root)
	writeCommand(&b, root, nil)

	page := b.String()
	if *out == "" {
		fmt.Print(page)
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		die(err)
	}
	if err := os.WriteFile(*out, []byte(page), 0o644); err != nil {
		die(err)
	}
	fmt.Fprintf(os.Stderr, "clidocs: wrote %s\n", *out)
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "clidocs:", err)
	os.Exit(1)
}

func writeGlobalFlags(b *strings.Builder, root *cobra.Command) {
	flags := root.PersistentFlags()
	if !flags.HasAvailableFlags() {
		return
	}
	b.WriteString("## Global flags {#global-flags}\n\nThese are accepted by every command.\n\n")
	writeFlagTable(b, flags)
}

// writeCommand emits one section per command, depth first, so that the page
// reads in the same order as `semaphore --help` walks the tree.
func writeCommand(b *strings.Builder, c *cobra.Command, path []string) {
	if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
		return
	}

	if len(path) > 0 {
		full := strings.Join(path, " ")
		fmt.Fprintf(b, "## `semaphore %s` {#%s}\n\n", full, anchor(full))

		if desc := description(c); desc != "" {
			fmt.Fprintf(b, "%s\n\n", desc)
		}
		fmt.Fprintf(b, "```\nsemaphore %s\n```\n\n", strings.TrimPrefix(c.UseLine(), "semaphore "))

		if len(c.Aliases) > 0 {
			fmt.Fprintf(b, "Aliases: %s.\n\n", codeList(c.Aliases))
		}
		if ex := strings.TrimSpace(c.Example); ex != "" {
			fmt.Fprintf(b, "Example:\n\n```bash\n%s\n```\n\n", ex)
		}
		if flags := c.NonInheritedFlags(); flags.HasAvailableFlags() {
			writeFlagTable(b, flags)
		}
		if subs := visibleSubcommands(c); len(subs) > 0 {
			b.WriteString("| Subcommand | Purpose |\n|---|---|\n")
			for _, s := range subs {
				fmt.Fprintf(b, "| [`semaphore %s %s`](#%s) | %s |\n",
					strings.Join(path, " "), s.Name(), anchor(strings.Join(append(path, s.Name()), " ")), firstLine(s))
			}
			b.WriteString("\n")
		}
	}

	for _, s := range visibleSubcommands(c) {
		writeCommand(b, s, append(path, s.Name()))
	}
}

func visibleSubcommands(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, s := range c.Commands() {
		if s.Hidden || s.Name() == "help" || s.Name() == "completion" {
			continue
		}
		out = append(out, s)
	}
	return out
}

func writeFlagTable(b *strings.Builder, flags *pflag.FlagSet) {
	b.WriteString("| Flag | Type | Default | Description |\n|---|---|---|---|\n")
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name += ", `-" + f.Shorthand + "`"
		}
		def := "—"
		if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "[]" {
			def = "`" + f.DefValue + "`"
		}
		usage := escape(f.Usage)
		if usage == "" {
			usage = "—"
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", name, f.Value.Type(), def, usage)
	})
	b.WriteString("\n")
}

func description(c *cobra.Command) string {
	text := c.Long
	if text == "" {
		text = c.Short
	}
	return escape(strings.TrimSpace(text))
}

func firstLine(c *cobra.Command) string {
	text := c.Short
	if text == "" {
		text = strings.SplitN(c.Long, "\n", 2)[0]
	}
	return escape(strings.TrimSpace(text))
}

func codeList(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

func escape(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", `\|`), "\n", " ")
}

var nonAnchor = regexp.MustCompile(`[^a-z0-9]+`)

func anchor(s string) string {
	return strings.Trim(nonAnchor.ReplaceAllString(strings.ToLower("semaphore "+s), "-"), "-")
}
