ALTER TABLE user ADD alert BOOLEAN NOT NULL DEFAULT 0 AFTER password;
ALTER TABLE project ADD alert BOOLEAN NOT NULL DEFAULT 0 AFTER name;

ALTER TABLE user ADD external BOOLEAN NOT NULL DEFAULT 0 AFTER password;