version: "3.4"

volumes:
  dredd:

services:
  server:
    environment:
      FORGE_ADMIN_PASSWORD: password
      FORGE_ADMIN_NAME: Developer
      FORGE_ADMIN_EMAIL: admin@localhost
      FORGE_ADMIN: admin
      FORGE_WEB_ROOT: http://0.0.0.0:3000

  dredd:
    build:
      context: ../../../
      dockerfile: deployment/docker/dredd/Dockerfile
    command:
      - --config
      - .dredd/dredd.docker.yml
    environment:
      FORGE_ACCESS_KEY_ENCRYPTION: ${FORGE_ACCESS_KEY_ENCRYPTION:-IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ=}
    volumes:
      - dredd:/data
