#!/bin/sh

set -e

echoerr() { printf "%s\n" "$*" >&2; }


SEMAPHORE_CONFIG_PATH="${SEMAPHORE_CONFIG_PATH:-/etc/semaphore}"
SEMAPHORE_RUNNER_CONFIG_FILE="${SEMAPHORE_CONFIG_PATH:-/etc/semaphore/runner.json}"
SEMAPHORE_TMP_PATH="${SEMAPHORE_TMP_PATH:-/tmp/semaphore}"

SEMAPHORE_REGISTRATION_TOKEN="${SEMAPHORE_REGISTRATION_TOKEN:-}"
SEMAPHORE_API_URL="${SEMAPHORE_API_URL:-}"
SEMAPHORE_RUNNER_ONE_OFF="${SEMAPHORE_RUNNER_ONE_OFF:-false}"

# Create a config if it does not exist in the current config path
if [ ! -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
    echoerr "Generating ${SEMAPHORE_CONFIG_PATH}/config.json ..."

    cat << EOF > "${SEMAPHORE_CONFIG_PATH}/config.json"
{
 	"tmp_path": "${SEMAPHORE_TMP_PATH}",
	"runner": {
		"registration_token": "${SEMAPHORE_REGISTRATION_TOKEN}",
		"config_file": "${SEMAPHORE_RUNNER_CONFIG_FILE}",
		"api_url": "${SEMAPHORE_API_URL}",
		"one_off": ${SEMAPHORE_RUNNER_ONE_OFF}
	}
}
EOF

    echoerr "Run Semaphore with semaphore runner --config ${SEMAPHORE_CONFIG_PATH}/config.json"
fi

# run our command
exec "$@"
