#!/bin/sh

set -e

echoerr() { printf "%s\n" "$*" >&2; }


SEMAPHORE_REGISTRATION_TOKEN="${SEMAPHORE_REGISTRATION_TOKEN:-}"
SEMAPHORE_API_URL="${SEMAPHORE_API_URL:-}"
SEMAPHORE_RUNNER_ONE_OFF="${SEMAPHORE_RUNNER_ONE_OFF:-false}"

# Create a config if it does not exist in the current config path
if [ ! -f "/etc/semaphore/config.json" ]; then
    echoerr "Generating /etc/semaphore/config.json ..."

    cat << EOF > "/etc/semaphore/config.json"
{
 	"tmp_path": "/data",
	"runner": {
		"registration_token": "${SEMAPHORE_REGISTRATION_TOKEN}",
		"config_file": "/etc/semaphore/runner.json",
		"api_url": "${SEMAPHORE_API_URL}",
		"one_off": "${SEMAPHORE_RUNNER_ONE_OFF}
	}
}
EOF

    echoerr "Run Semaphore with semaphore --config /etc/semaphore/config.json"
fi

# run our command
exec "$@"
