#!/usr/bin/env bash

cat <<EOF
{
        "bolt": {
          "host": "/data/database.sqlite3"
        },
        "dialect": "sqlite",
        "access_key_encryption": "${SEMAPHORE_ACCESS_KEY_ENCRYPTION}"
}
EOF
