#!/usr/bin/env bash

cat <<EOF
{
	"mysql": {
		"host": "mysql:3306",
		"user": "semaphore",
		"pass": "semaphore",
		"name": "semaphore"
	},
	"dialect": "mysql",
	"access_key_encryption": "${SEMAPHORE_ACCESS_KEY_ENCRYPTION}"
}
EOF

