#!/usr/bin/env bash

cat <<EOF
{
	"postgres": {
		"host": "postgres:5432",
		"user": "semaphore",
		"pass": "semaphore",
		"name": "semaphore",
    "options": {
      "sslmode": "disable"
    }
	},
	"dialect": "postgres",
	"access_key_encryption": "${SEMAPHORE_ACCESS_KEY_ENCRYPTION}"
}
EOF
