#!/usr/bin/env bash

cat <<EOF
{
        "bolt": {
          "host": "/data/database.boltdb"
        },
        "dialect": "bolt",
        "access_key_encryption": "${SEMAPHORE_ACCESS_KEY_ENCRYPTION}"
}
EOF
