version: "3.4"

volumes:
  mariadb:
  postgres:

services:
  mariadb:
    image: mariadb:10.8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: forge
      MARIADB_PASSWORD: forge
      MARIADB_DATABASE: forge
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  postgres:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: forge
      POSTGRES_DB: forge
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432
