version: "3.4"

volumes:
  postgres:

services:
  server:
    environment:
      FORGE_DB_DIALECT: postgres
      FORGE_DB_HOST: db
      FORGE_DB_PORT: 5432
      FORGE_DB_USER: ${POSTGRES_USERNAME:-forge}
      FORGE_DB_PASS: ${POSTGRES_PASSWORD:-forge}
      FORGE_DB: ${POSTGRES_DATABASE:-forge}
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-forge}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-forge}
      POSTGRES_DB: ${POSTGRES_DATABASE:-forge}
    volumes:
      - postgres:/var/lib/postgresql
