#!/bin/sh
set -e
echoerr() { printf "%s\n" "$*" >&2; }

#
# Read environment variables from file if envrionment variable ${1}_FILE is set
#
file_env() {
    local var=""
    local fileVar=""

    eval var="\$${1}"
    eval fileVar="\$${1}_FILE"

    local def="${2:-}"

    if [ -n "${var:-}" ] && [ -n "${fileVar:-}" ]; then
        echo >&2 "error: both ${1} and ${1}_FILE are set (but are exclusive)"
        exit 1
    fi

    local val="$def"

    if [ -n "${var:-}" ]; then
        val="${var}"
    elif [ -n "${fileVar:-}" ]; then
        val="$(cat "${fileVar}")"
    fi

    if [ -n "${val:-}" ]; then
        export "${1}"="$val"
    fi

    unset "${1}_FILE"
}

export FORGE_CONFIG_PATH="${FORGE_CONFIG_PATH:-/etc/forge}"
export FORGE_DB_PATH="${FORGE_DB_PATH:-/var/lib/forge}"
export FORGE_DB_PORT="${FORGE_DB_PORT:-}"

file_env 'FORGE_DB_USER'
file_env 'FORGE_DB_PASS'
file_env 'FORGE_ADMIN'
export FORGE_ADMIN_EMAIL="${FORGE_ADMIN_EMAIL:-admin@localhost}"
export FORGE_ADMIN_NAME="${FORGE_ADMIN_NAME:-Forge Admin}"
file_env 'FORGE_ADMIN_PASSWORD'
export FORGE_LDAP_ACTIVATED="${FORGE_LDAP_ACTIVATED:-no}"
export FORGE_LDAP_HOST="${FORGE_LDAP_HOST:-}"
export FORGE_LDAP_PORT="${FORGE_LDAP_PORT:-}"
export FORGE_LDAP_DN_BIND="${FORGE_LDAP_DN_BIND:-}"
file_env 'FORGE_LDAP_PASSWORD'
export FORGE_LDAP_DN_SEARCH="${FORGE_LDAP_DN_SEARCH:-}"
export FORGE_LDAP_MAPPING_USERNAME="${FORGE_LDAP_MAPPING_USERNAME:-uid}"
export FORGE_LDAP_MAPPING_FULLNAME="${FORGE_LDAP_MAPPING_FULLNAME:-cn}"
export FORGE_LDAP_MAPPING_EMAIL="${FORGE_LDAP_MAPPING_EMAIL:-mail}"
file_env 'FORGE_ACCESS_KEY_ENCRYPTION'


[ -d "${FORGE_CONFIG_PATH}" ] || mkdir -p "${FORGE_CONFIG_PATH}" || {
    echo "Can't create Forge config path ${FORGE_CONFIG_PATH}."
    exit 1
}

[ -d "${FORGE_DB_PATH}" ] || mkdir -p "${FORGE_DB_PATH}" || {
    echo "Can't create Forge data path ${FORGE_DB_PATH}."
    exit 1
}


#
# Extract database host and port from config.json if they are not set.
# Set default FORGE_DB_DIALECT and FORGE_DB_HOST if empty.
#
if [ -z "${FORGE_DB_DIALECT}" ]; then
    if [ -f "${FORGE_CONFIG_PATH}/config.json" ]; then
        FORGE_DB_DIALECT=$(cat "${FORGE_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
    fi
fi

export FORGE_DB_DIALECT="${FORGE_DB_DIALECT:-mysql}"

if [ -z "${FORGE_DB_HOST}" ]; then
    if [ -f "${FORGE_CONFIG_PATH}/config.json" ]; then
        FORGE_DB_HOST=$(cat "${FORGE_CONFIG_PATH}/config.json" | jq ".${FORGE_DB_DIALECT}.host // \"\"" -r)
    fi
fi

if [ -z "${FORGE_DB_HOST}" ]; then
    if [ "${FORGE_DB_DIALECT}" = 'bolt' ]; then
        export FORGE_DB_HOST=${FORGE_DB_PATH}/database.boltdb
    elif [ "${FORGE_DB_DIALECT}" = 'sqlite' ]; then
        export FORGE_DB_HOST=${FORGE_DB_PATH}/database.sqlite
    else
        export FORGE_DB_HOST="${FORGE_DB_HOST:-0.0.0.0}"
    fi
fi


#
# Remove port number from FORGE_DB_HOST and put it to FORGE_DB_PORT
#
case "$FORGE_DB_HOST" in
  *:*)
    FORGE_DB_PORT=$(echo "$FORGE_DB_HOST" | cut -d ':' -f 2)
    FORGE_DB_HOST=$(echo "$FORGE_DB_HOST" | cut -d ':' -f 1)
    ;;
  *)
esac


#
# Set FORGE_DB_PORT if it is not set
#
if [ -z "${FORGE_DB_PORT}" ]; then
    case ${FORGE_DB_DIALECT} in
        mysql)
            FORGE_DB_PORT=3306
            ;;
        postgres)
            FORGE_DB_PORT=5432
            ;;
        bolt)
            ;;
        sqlite)
            ;;
        *)
            echoerr "Unknown database dialect: ${FORGE_DB_DIALECT}"
            exit 1
            ;;
    esac
fi


#
# Ping database if it is not BoltDB
#
if [ "${FORGE_DB_DIALECT}" != 'bolt' ] && [ "${FORGE_DB_DIALECT}" != 'sqlite' ]; then
    echoerr "Pinging database on ${FORGE_DB_HOST} port ${FORGE_DB_PORT}..."
    TIMEOUT=30


    while ! $(nc -z "$FORGE_DB_HOST" "$FORGE_DB_PORT") >/dev/null 2>&1; do
        TIMEOUT=$(expr $TIMEOUT - 1)

        if [ $TIMEOUT -eq 0 ]; then
            echoerr "Could not connect to database server. Exiting."
            exit 1
        fi

        echo -n "."
        sleep 1
    done
    
    export FORGE_DB_HOST="${FORGE_DB_HOST}:${FORGE_DB_PORT}"
fi


#
# Generate new config.json if it does not exist
#
if [ ! -f "${FORGE_CONFIG_PATH}/config.json" ]; then
    echoerr "Generating setup file ${TMP_STDIN_CONFIG_FILE} ..."

    TMP_STDIN_CONFIG_FILE=$(mktemp)


    FORGE_TMP_PATH=${FORGE_TMP_PATH:-/tmp/forge}
    [ -d "${FORGE_TMP_PATH}" ] || mkdir -p "${FORGE_TMP_PATH}" || {
        echo "Can't create Forge tmp path ${FORGE_TMP_PATH}."
        exit 1
    }


    case ${FORGE_DB_DIALECT} in
        mysql)
            FORGE_DB_DIALECT_ID=1
            ;;
        bolt)
            FORGE_DB_DIALECT_ID=2
            ;;
        postgres)
            FORGE_DB_DIALECT_ID=3
            ;;
        sqlite)
            FORGE_DB_DIALECT_ID=4
            ;;
        *)
            echoerr "Unknown database dialect: ${FORGE_DB_DIALECT}"
            exit 1
            ;;
    esac


    cat << EOF > "${TMP_STDIN_CONFIG_FILE}"
${FORGE_DB_DIALECT_ID}
EOF

    if [ "${FORGE_DB_DIALECT}" = "bolt" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${FORGE_DB_HOST}
EOF
    elif [ "${FORGE_DB_DIALECT}" = "sqlite" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${FORGE_DB_HOST}
EOF
    else
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${FORGE_DB_HOST}
${FORGE_DB_USER}
${FORGE_DB_PASS}
${FORGE_DB:-forge}
EOF
    fi

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${FORGE_TMP_PATH}
${FORGE_WEB_ROOT:-}
no
no
no
no
no
${FORGE_LDAP_ACTIVATED}
EOF

    if [ "${FORGE_LDAP_ACTIVATED}" = "yes" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${FORGE_LDAP_HOST}:${FORGE_LDAP_PORT}
${FORGE_LDAP_NEEDTLS:-no}
${FORGE_LDAP_DN_BIND}
${FORGE_LDAP_PASSWORD}
${FORGE_LDAP_DN_SEARCH}
${FORGE_LDAP_SEARCH_FILTER:-(uid=%s)}
${FORGE_LDAP_MAPPING_DN:-dn}
${FORGE_LDAP_MAPPING_USERNAME}
${FORGE_LDAP_MAPPING_FULLNAME}
${FORGE_LDAP_MAPPING_EMAIL}
EOF
    fi;

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${FORGE_CONFIG_PATH}
${FORGE_ADMIN}
${FORGE_ADMIN_EMAIL}
${FORGE_ADMIN_NAME}
${FORGE_ADMIN_PASSWORD}
EOF


    echoerr "Executing forge setup"
    if test "$#" -ne 1; then
        /usr/local/bin/forge setup - < "${TMP_STDIN_CONFIG_FILE}"
    else
        "$1" setup - < "${TMP_STDIN_CONFIG_FILE}"
    fi

    rm -f "${TMP_STDIN_CONFIG_FILE}"
fi


#
# Install additional python dependencies
#
if test -f "${FORGE_CONFIG_PATH}/requirements.txt"; then
    echoerr "Installing additional python dependencies"
    pip3 install --upgrade \
        -r "${FORGE_CONFIG_PATH}/requirements.txt"
else
    echoerr "No additional python dependencies to install"
fi


#
# Start Forge server
#
echoerr "Starting forge server"
if test "$#" -ne 1; then
    exec /usr/local/bin/forge server  --config "${FORGE_CONFIG_PATH}/config.json"
else
    exec "$@"
fi
