package db

import (
	"time"

	"github.com/go-gorp/gorp/v3"
)

// TaskFile represents a file artifact generated by a task
type TaskFile struct {
	ID          int       `db:"id" json:"id"`
	TaskID      int       `db:"task_id" json:"task_id"`
	ProjectID   int       `db:"project_id" json:"project_id"`
	Filename    string    `db:"filename" json:"filename"`
	OriginalPath string   `db:"original_path" json:"original_path"`
	FileSize    int64     `db:"file_size" json:"file_size"`
	MimeType    string    `db:"mime_type" json:"mime_type"`
	Checksum    string    `db:"checksum" json:"checksum"`
	Created     time.Time `db:"created" json:"created"`
	Description *string   `db:"description" json:"description,omitempty"`
}

// PreInsert sets the created timestamp before inserting
func (tf *TaskFile) PreInsert(s gorp.SqlExecutor) error {
	tf.Created = time.Now()
	return nil
}

// PreUpdate sets the updated timestamp before updating
func (tf *TaskFile) PreUpdate(s gorp.SqlExecutor) error {
	return nil
}
