version: "3.4"

services:
  runner:
    image: docker.io/forgeui/runner:${FORGE_VERSION:-latest}
    restart: always
    environment:
      FORGE_WEB_ROOT: ${FORGE_WEB_ROOT:-http://server:3000}
      FORGE_RUNNER_API_URL: ${FORGE_RUNNER_API_URL:-http://server:3000/internal}
      FORGE_RUNNER_REGISTRATION_TOKEN: ${FORGE_RUNNER_REGISTRATION_TOKEN:-H1wDyorbg6gTSwJlVwle2Fne}

  server:
    environment:
      FORGE_RUNNER_REGISTRATION_TOKEN: ${FORGE_RUNNER_REGISTRATION_TOKEN:-H1wDyorbg6gTSwJlVwle2Fne}
