version: "3.4"

volumes:
  server:

services:
  server:
    image: docker.io/forgeui/forge:${FORGE_VERSION:-latest}
    restart: always
    environment:
      FORGE_ADMIN_NAME: ${FORGE_ADMIN_NAME:-Admin}
      FORGE_ADMIN: ${FORGE_ADMIN_USERNAME:-admin}
      FORGE_ADMIN_PASSWORD: ${FORGE_ADMIN_PASSWORD:-p455w0rd}
      FORGE_ADMIN_EMAIL: ${FORGE_ADMIN_EMAIL:-admin@localhost}
      FORGE_WEB_ROOT: ${FORGE_WEB_ROOT:-http://0.0.0.0:3000}
      FORGE_ACCESS_KEY_ENCRYPTION: ${FORGE_ACCESS_KEY_ENCRYPTION:-IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ=}
    volumes:
      - server:/var/lib/forge
    ports:
      - "3000:3000"
