file:
  /usr/local/bin/runner-wrapper:
    exists: true
    owner: forge
    group: root
    filetype: file
  /usr/local/bin/forge:
    exists: true
    owner: forge
    group: root
    filetype: file

package:
  go:
    installed: false
  libc-dev:
    installed: false
  nodejs:
    installed: false

  curl:
    installed: true
  git:
    installed: true
  mysql-client:
    installed: true
  openssh-client-default:
    installed: true
  python3:
    installed: true
  py3-pip:
    installed: true
  rsync:
    installed: true
  sshpass:
    installed: true
  tar:
    installed: true
  tini:
    installed: true
  tzdata:
    installed: true
  unzip:
    installed: true
  wget:
    installed: true
  zip:
    installed: true

user:
  forge:
    exists: true
    uid: 1001
    gid: 0
    home: /home/forge

command:
  forge:
    exit-status: 0
    timeout: 10000
